### ISSUE TITLE
Not correct find.

### ISSUE THREAD

**Issue by olehbozhok** [BurntSushi/rust-pcre2#21]
I can`t pass this test.
On https://regex101.com/ these regexp work correctly.
Could someone help me?

Using pcre2 = "0.2.3"

```
#[test]
fn reg_test() {
    assert!(Regex::new(r"(с[яьи])$")
        .unwrap()
        .find("чкається".as_bytes())
        .unwrap()
        .is_some());
}
```

**Comment by BurntSushi** [comment]
You need to enable either the [`ucp`](https://docs.rs/pcre2/0.2.3/pcre2/bytes/struct.RegexBuilder.html#method.ucp) or [`utf`](https://docs.rs/pcre2/0.2.3/pcre2/bytes/struct.RegexBuilder.html#method.utf) options. It's not clear to me why _either_ works, but I am not a PCRE2 maintainer. I just maintain these bindings to it.
