### ISSUE TITLE
pcre2-sys not correctly retrieved, compilation fails in MSYS2/MinGW, GCC 11

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/rust-pcre2#24]
Originally filed here: https://github.com/BurntSushi/ripgrep/issues/2222

#### What version of ripgrep are you using?

HEAD sources = a726d03641e081aa0f4c4a1b9f24f5a905fd5d04

#### How did you install ripgrep?

vcs_fetch routine in media-autobuild_suite uses git to retrieve HEAD sources:
```
vcs_fetch 
++ git rev-parse --git-dir
+ [[ -f .git/shallow ]]
+ unshallow=
+ git fetch --all -Ppft
Fetching origin
+ git remote set-head -a origin
origin/HEAD set to master
```

#### What operating system are you using ripgrep on?

MSYS2/MinGW on Windows (7 or 10)

#### Describe your bug.

[media-autobuild_suite issue 2195](https://github.com/m-ab-s/media-autobuild_suite/issues/2195) - please note especially https://github.com/m-ab-s/media-autobuild_suite/issues/2195#issuecomment-1135139851

Parts of build/ripgrep-git/ab-suite.rust.build.log:
```
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
/opt/cargo/bin/cargo.exe build --release --target=i686-pc-windows-gnu --jobs=1 --features pcre2

...

error: failed to run custom build command for `pcre2-sys v0.2.5`

Caused by:
  process didn't exit successfully: `E:\MABS\build\ripgrep-git\target\release\build\pcre2-sys-a3cacd8a0f6685c4\build-script-build` (exit code: 1)

...

  running: "ccache" "gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m32" "-mthreads" "-mtune=generic" "-O2" "-pipe" "-I" "pcre2/src" "-I" "E:\\MABS\\build\\ripgrep-git\\target\\i686-pc-windows-gnu\\release\\build\\pcre2-sys-7567a6bd01fdc6f7\\out\\include" "-DPCRE2_CODE_UNIT_WIDTH=8" "-DHAVE_STDLIB_H=1" "-DHAVE_MEMMOVE=1" "-DHEAP_LIMIT=20000000" "-DLINK_SIZE=2" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_DEPTH=10000000" "-DMAX_NAME_COUNT=10000" "-DMAX_NAME_SIZE=32" "-DNEWLINE_DEFAULT=2" "-DPARENS_NEST_LIMIT=250" "-DPCRE2_STATIC=1" "-DSTDC_HEADERS=1" "-DSUPPORT_PCRE2_8=1" "-DSUPPORT_UNICODE=1" "-DHAVE_WINDOWS_H=1" "-DSUPPORT_JIT=1" "-o" "E:\\MABS\\build\\ripgrep-git\\target\\i686-pc-windows-gnu\\release\\build\\pcre2-sys-7567a6bd01fdc6f7\\out\\src\\pcre2_chartables.o" "-c" "E:\\MABS\\build\\ripgrep-git\\target\\i686-pc-windows-gnu\\release\\build\\pcre2-sys-7567a6bd01fdc6f7\\out\\src\\pcre2_chartables.c"
  exit code: 1
  running: "ccache" "gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m32" "-mthreads" "-mtune=generic" "-O2" "-pipe" "-I" "pcre2/src" "-I" "E:\\MABS\\build\\ripgrep-git\\target\\i686-pc-windows-gnu\\release\\build\\pcre2-sys-7567a6bd01fdc6f7\\out\\include" "-DPCRE2_CODE_UNIT_WIDTH=8" "-DHAVE_STDLIB_H=1" "-DHAVE_MEMMOVE=1" "-DHEAP_LIMIT=20000000" "-DLINK_SIZE=2" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_DEPTH=10000000" "-DMAX_NAME_COUNT=10000" "-DMAX_NAME_SIZE=32" "-DNEWLINE_DEFAULT=2" "-DPARENS_NEST_LIMIT=250" "-DPCRE2_STATIC=1" "-DSTDC_HEADERS=1" "-DSUPPORT_PCRE2_8=1" "-DSUPPORT_UNICODE=1" "-DHAVE_WINDOWS_H=1" "-DSUPPORT_JIT=1" "-o" "E:\\MABS\\build\\ripgrep-git\\target\\i686-pc-windows-gnu\\release\\build\\pcre2-sys-7567a6bd01fdc6f7\\out\\pcre2/src\\pcre2_auto_possess.o" "-c" "pcre2/src\\pcre2_auto_possess.c"
  exit code: 1

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git


  error occurred: Command "ccache" "gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m32" "-mthreads" "-mtune=generic" "-O2" "-pipe" "-I" "pcre2/src" "-I" "E:\\MABS\\build\\ripgrep-git\\target\\i686-pc-windows-gnu\\release\\build\\pcre2-sys-7567a6bd01fdc6f7\\out\\include" "-DPCRE2_CODE_UNIT_WIDTH=8" "-DHAVE_STDLIB_H=1" "-DHAVE_MEMMOVE=1" "-DHEAP_LIMIT=20000000" "-DLINK_SIZE=2" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_DEPTH=10000000" "-DMAX_NAME_COUNT=10000" "-DMAX_NAME_SIZE=32" "-DNEWLINE_DEFAULT=2" "-DPARENS_NEST_LIMIT=250" "-DPCRE2_STATIC=1" "-DSTDC_HEADERS=1" "-DSUPPORT_PCRE2_8=1" "-DSUPPORT_UNICODE=1" "-DHAVE_WINDOWS_H=1" "-DSUPPORT_JIT=1" "-o" "E:\\MABS\\build\\ripgrep-git\\target\\i686-pc-windows-gnu\\release\\build\\pcre2-sys-7567a6bd01fdc6f7\\out\\src\\pcre2_chartables.o" "-c" "E:\\MABS\\build\\ripgrep-git\\target\\i686-pc-windows-gnu\\release\\build\\pcre2-sys-7567a6bd01fdc6f7\\out\\src\\pcre2_chartables.c" with args "gcc" did not execute successfully (status code exit code: 1).
```

#### What are the steps to reproduce the behavior?

compiling with rust and gcc 11 in media-autobuild_suite as verbosely logged

#### What is the actual behavior?

see above, and [logs.zip](https://0x0.st/oa3a.zip) for more details

#### What is the expected behavior?

Successful compilation.

**Comment by BurntSushi** [comment]
@LigH-de I personally won't be debugging this any time soon. But it looks like the pcre2-sys build script could be improved: https://github.com/BurntSushi/rust-pcre2/blob/2f87eb93e5b688a23e02354af116176e13c85d38/pcre2-sys/build.rs

Right now, it's logic is basically, "unless you requested a static build, we use `pkg-config` to look for a pre-installed PCRE2 library and dynamically link to it." And then, "otherwise, we pull the PCRE2 sources bundled with the crate to statically compile PCRE2."

So the git error is mostly a bad failure mode. What it really means is, "I don't know how to find the PCRE2 source code." So you'll need to modify the `pcre2-sys` crate's build script to work in your environment. If the patch is small and reasonable, I'd be happy to accept it here.

**Comment by LigH-de** [comment]
Thank you; I am no developer so can't help fixing it. I can only report that building it in m-ab-s used to work for years, until a few days ago. I hope anyone can imagine when something related changed in a way that caused it to fail now.

**Comment by BurntSushi** [comment]
Nothing in `pcre2-sys` has changed at least.

Note that you aren't just building ripgrep. You're building ripgrep with its _optional_ PCRE2 feature enabled. So you could disable it.

**Comment by 1480c1** [comment]
From what I can tell, I think as long as we install pcre2 from msys2, it might work? I might need to export `PKG_CONFIG_ALL_STATIC` to ensure it uses --static

Main thing I can see to improve the build.rs would be on

https://github.com/BurntSushi/rust-pcre2/blob/2f87eb93e5b688a23e02354af116176e13c85d38/pcre2-sys/build.rs#L72

to make it check if it was git cloned in the first place

**Comment by 1480c1** [comment]
> From what I can tell, I think as long as we install pcre2 from msys2, it might work? I might need to export PKG_CONFIG_ALL_STATIC to ensure it uses --static

Seems that was not enough, for some reason, despite exporting `PCRE2_SYS_STATIC=0`, and installing the package and being able to run
```bash
$ pkg-config --libs --static libpcre2-8
-lpcre2-8
```
it still tries to continue on
