### ISSUE TITLE
support for running JIT on invalid UTF-8

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/rust-pcre2#5]
It looks like this is a new feature coming down the pike: https://lists.exim.org/lurker/message/20180917.192454.6e424732.en.html

In theory this could be a nice performance win in ripgrep such that transcoding no longer needs to be done. Note though that this only works with the JIT; the regular matcher still needs valid UTF-8.

**Comment by zherczeg** [comment]
(Note) A new version of PCRE2 is released which contains this feature:
https://lists.exim.org/lurker/message/20190416.154043.a260ee6c.en.html
